name: Build and Sign Android App

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "8.0.201"

    - name: Install MAUI Workloads
      run: sudo dotnet workload install maui-android
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Decode Keystore File
      run: |
        echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > ./ApkDownload/release.keystore


    - name: Build and Sign APK
      run: |
        dotnet publish ./ApkDownload -f net8.0-android -c Release \
        -p:AndroidKeyStore=true \
        -p:AndroidSigningKeyStore=release.keystore  \
        -p:AndroidSigningKeyAlias=${{ secrets.ANDROID_KEY_ALIAS }} \
        -p:AndroidSigningKeyPass=${{ secrets.ANDROID_KEY_PASS }} \
        -p:AndroidSigningStorePass=${{ secrets.ANDROID_STORE_PASS }}

    - name: Archive production artifacts from APK
      uses: actions/upload-artifact@v4
      with:
        name: ApkDownloader
        path: ./ApkDownload/bin/Release/net8.0-android/
